stages:
  - build
  - trigger_deployment
  
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: your_docker_image/release-web 

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# Définition des étapes de la pipeline

build_job:
  stage: build
  script:
    - export VERSION=$(cat VERSION)
    - docker build -t "$DOCKER_IMAGE:$VERSION" -f DockerFile .
    - docker images
    - docker push $DOCKER_IMAGE:$VERSION
  only:
    # Ce job ne s'exécute que sur la branche 'main'
    - main

# Job pour déclencher la pipeline de déploiement
trigger_deployment:
  stage: trigger_deployment
  image: alpine:latest # Utilisation d'une image légère contenant apk
  before_script:
    - apk add --no-cache curl  # Installer curl
  script:
    # Lecture de la version depuis le fichier VERSION
    - cat VERSION
    - export VERSION=$(cat VERSION)
    # Déclenchement de la pipeline CD en passant la version comme variable d'environnement
    - curl -X POST -F token=your_trigger_token -F ref=main -F "variables[VERSION]=$VERSION" https://gitlab.com/api/v4/projects/your_project_id/trigger/pipeline # URL et token anonymisés
  only:
    # Ce job ne s'exécute que sur la branche 'main'
    - main