apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: <EMAIL>  # Remplacez par votre adresse email
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}  # Un sélecteur vide signifie que ce solveur correspond à tous les domaines
      dns01:
        cloudflare:
          email: <EMAIL>  # Remplacez par votre adresse email
          apiTokenSecretRef:
            name: cloudflare-api-token-prod-secret
            key: api-token

---

# Secret pour le jeton d'API Cloudflare en production
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-prod-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: <API-TOKEN>  # Remplacez par votre jeton API Cloudflare

---

# ClusterIssuer pour Let's Encrypt en staging
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stg
spec:
  acme:
    email: <EMAIL>  # Remplacez par votre adresse email
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-issuer-acct-key
    solvers:
    - dns01:
        cloudflare:
          email: <EMAIL>  # Remplacez par votre adresse email
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - 'example.com'  # Remplacez par votre domaine
        - '*.example.com'  # Remplacez par votre domaine

---

# Secret pour le jeton d'API Cloudflare en staging
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: <API-TOKEN>  # Remplacez par votre jeton API Cloudflare

---

# Certificate pour Let's Encrypt en production
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-prod
  namespace: cert-manager
spec:
  secretName: acme-crt-secret-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.example.com'  # Remplacez par votre domaine
  dnsNames:
  - "example.com"  # Remplacez par votre domaine
  - "*.example.com"  # Remplacez par votre domaine

---

# Certificate pour Let's Encrypt en staging
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-com
  namespace: default
spec:
  secretName: domain-com
  issuerRef:
    name: letsencrypt-stg
    kind: ClusterIssuer
  commonName: '*.example.com'  # Remplacez par votre domaine
  dnsNames:
  - "*.example.com"  # Remplacez par votre domaine
